build:
     project: DacpacDemo2012\DacpacDemo2012.sln

services:
  - mssql2012

artifacts:
  - path: DacpacDemo2012\bin\debug\DacpacDemo2012.dacpac
    name: DacpacDemo2012

deploy:
  - provider: SqlDatabase
    artifact: MyDatabase
    connection_string: 'Server=vagrant-2012-r2\SNKTHEONE;Database=DacpacDemo2012;Integrated Security=SSPI'
